#!/bin/sh /etc/rc.common

START=95
STOP=15
USE_PROCD=1

PROG=/root/display_info.py
PIDFILE=/var/run/display_info.pid

start_service() {
    procd_open_instance
    procd_set_param command python3 $PROG
    procd_set_param pidfile $PIDFILE
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_close_instance
}

stop_service() {
    service_stop $PROG
}

service_triggers() {
    procd_add_reload_trigger "display_info"
} 